### ISSUE TITLE
npm i fails at commit d283473dc78b8afd4b02e020b780fea52538a95c

### ISSUE THREAD

**Issue by OR13** [nareshbhatia/react-force#1]
```
(typescript) Error: src/DateUtils.ts:1:20 - error TS2307: Cannot find module 'moment' or its corresponding type declarations.

1 import moment from 'moment';
                     ~~~~~~~~

Error: src/DateUtils.ts:1:20 - error TS2307: Cannot find module 'moment' or its corresponding type declarations.

1 import moment from 'moment';
```

**Comment by OR13** [comment]
I'm one of the authors of https://material-did.com/

I found you through https://github.com/formium/tsdx/pull/778#issuecomment-672106970

I'm also one of the folks waiting on a good TSDX template for mono repos.

Have you resolved the treeshaking / bundle size issues with default TSDX configurations?

**Comment by nareshbhatia** [comment]
Hmmm, I wonder if this is an npm issue. I always use yarn (and a yarn.lock
is checked in). Can you please try with yarn and see if the same thing
happens?

As far as I can tell, treeshaking is working with the default TSDX
configuration. I tried it with a sample app, pulling in only a single
component. I can then see in the app bundle that only the component and its
dependencies are packaged. That's the extent of my testing.

**Comment by OR13** [comment]
confirmed, `yarn` works, but `npm i` fails.

a few years ago, i vowed never to use yarn, because of all the compatibility issues with npm... If you have a spare cycle to convince me otherwise, I would appreciate it.

**Comment by nareshbhatia** [comment]
I used to have the same opinion. They are indeed very close in functionality, but I think yarn has a slight edge. Specifically, TSDX (and hence this monorepo) depends on the yarn "workspaces" feature to link up the sub repos. There is no easy equivalent of this in npm. Another example is yarn "resolutions" to control exactly which dependency gets picked up - again no equivalent in npm.

You can also refer to my article [Sharing UI Components with Lerna and Yarn Workspaces](https://medium.com/naresh-bhatia/sharing-ui-components-with-lerna-and-yarn-workspaces-be1ebca06efe) for some more details on yarn workspaces.

HTH.

**Comment by OR13** [comment]
Thanks! Very familiar with lerna.... currently waiting for TSDX to release a mono repo template before refactoring our component library, hoping it will end up looking very similar to this project, but with a focus on slightly more crypto / identity security UI components.

You have done an excellent job with react-force, I'm trying to figure out how I can rely on it more, and keep our repo focused on specialized higher order components which would probably seem out of place here in this repo. 

If you don't intend to fix this issue, feel free to close.

**Comment by nareshbhatia** [comment]
I intend to use SemVer religiously, so you can rely on the components offered in this repo. Given your focus on crypto/identity, I think it deserves a dedicated repo.

Given that I am relying on yarn workspaces, I can't make this repo work with npm. Hence closing this issue.

Good luck with your efforts.
